# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
