# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160825_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='SignUpForm',
        ),
    ]
