# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160825_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Enter email here'),
        ),
    ]
