# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160818_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sell_price',
            field=models.FloatField(),
        ),
    ]
