# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20160823_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon_discount',
            new_name='discount',
        ),
    ]
